---
version: "3"

vars:
  ANSIBLE_DIR: "{{.ROOT_DIR}}/infrastructure/ansible"
  CLUSTER_DIR: "{{.ROOT_DIR}}/kubernetes"
  CLI_DIR: "${HOME}/.local/bin"
  PROJECT_DIR: "{{.ROOT_DIR}}"

env:
  KUBECONFIG: "{{.ROOT_DIR}}/kubeconfig"

includes:
  ansible: .taskfiles/Ansible/Tasks.yml
  cli: .taskfiles/CLI/Tasks.yml

tasks:
  default:
    silent: true
    cmds: ["task -l"]
