---
version: '3'

vars:
  ANSIBLE_DIR: '{{.ROOT_DIR}}/infrastructure/ansible'
  CLUSTER_DIR: '{{.ROOT_DIR}}/kubernetes'
  CLI_DIR: '${HOME}/.local/bin'
  PROJECT_DIR: '{{.ROOT_DIR}}'
  POSTGRES_IP: '10.8.20.216'


env:
  KUBECONFIG: '{{.ANSIBLE_DIR}}/kubernetes/kubeconfig'

includes:
  an: .taskfiles/Ansible/Tasks.yml
  cl: .taskfiles/CLI/Tasks.yml

tasks:
  default:
    silent: true
    cmds: ['task -l']
